name: glitcher
description: Glitcher - Social App for Gamers!

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.7
  fluttertoast: ^3.1.3
  flutter_svg: ^0.14.3
  firebase_storage: ^3.0.6
  image_picker: ^0.6.1+4
  path: ^1.6.2
  video_player: ^0.10.2+3
  chewie: ^0.9.8+1
  flutter_icons: 0.2.0
  youtube_player_flutter: ^6.0.3+2
  cloud_firestore: ^0.12.9+5
  toast: ^0.1.5
  audioplayer: ^0.5.2
  modal_progress_hud: ^0.1.3
  soundpool: ^0.5.3
  dropdownfield: ^1.0.3
  autocomplete_textfield: ^1.7.3
  dropdown_formfield: ^0.1.1
  cached_network_image: ^2.0.0
  share: ^0.6.3+4
  firebase_dynamic_links: ^0.5.0+8
  curved_navigation_bar: ^0.3.1
  badges: ^1.1.0
  dynamic_theme: ^1.0.0
  permission: ^0.1.5
  random_string: ^2.0.1
  flutter_image_compress: ^0.6.5+1
  image_cropper: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1

flutter:

  uses-material-design: true

  assets:
   - assets/img/login_logo.png
   - assets/images/
   - assets/sounds/

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
