name: glitcher
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_storage: ^3.0.6
  image_picker: ^0.6.1+4
  path: ^1.6.2
  video_player: ^0.10.2+3
  flutter_icons: 0.2.0
  youtube_player_flutter: ^4.1.0
  cloud_firestore: ^0.12.9+5
  toast: ^0.1.5
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

